name: build-test

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    defaults:
      run:
        working-directory: ./src
        
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: dotnet build
