name: package

on:
  release:
    types: [published]

jobs:
  package:
    defaults:
      run:
        working-directory: ./src
    runs-on: windows-latest
        
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ github.ref_name }} --output .

    - name: Push package
      run: dotnet nuget push OperationResult.${{ github.ref_name }}.nupkg --source https://nuget.pkg.github.com/markmnl/index.json --api-key ${{ secrets.GITHUB_TOKEN }}

